### ISSUE TITLE
Excuse me, when will the spoken audio be released?

### ISSUE THREAD

**Issue by xian-sh** [marmot-xy/Spoken-Video-Grounding#1]
After reading your work, I am very pleased with the new task you proposed, I would like to ask you, could the relevant data set of the paper be disclosed soon? Thank you very much!

**Comment by marmot-xy** [comment]
We are now preparing a new paper based on this dataset for ACL 2023, the dataset will be released in about one month. Also could you send an SCP command to me? Then I can directly share the dataset with you.
