### ISSUE TITLE
Ask some doubts about datasets config

### ISSUE THREAD

**Issue by xian-sh** [marmot-xy/Spoken-Video-Grounding#2]
Dear author:
When I look at the following part of the code in "config/default.py":
**_c.dataset.feature_path = "/home/data/activity-c3d"
_c.dataset.vocab_path = "/home/glove_model.bin"
_c.dataset.audio_path = "/home/data/wavs_16k"
_c.dataset.data_path_template = "/home/new_{}_data.json"**,
I'm not sure where the _gloe_model.bin_ file is,could you tell me some details about this file?

note:I have downloaded the glove.42B.300d.zip file,but it does not match the file name mentioned in the code.

**Comment by marmot-xy** [comment]
The glove_bin file can be downloaded from here: https://drive.google.com/file/d/19mokq1Cx3Q2XjaefiA4D7gnwxaIFA6qs/view?usp=sharing

**Comment by xian-sh** [comment]
Thank you very much!
